[project]
name = "tortoise-database-url"
description = "Make it easy to generate database url."
authors = [{name="Waket Zheng", email="waketzheng@gmail.com"}]
readme = "README.md"
dynamic = ["version"]
keywords = ["database-url", "database_url", "tortoise-orm"]
requires-python = ">=3.9"
dependencies = []

[project.urls]
homepage = "https://github.com/waketzheng/database-url"
repository = "https://github.com/waketzheng/database-url.git"

[tool.poetry]
version = "0"
packages = [
    { include = "database_url" }
]

[tool.poetry.group.dev.dependencies]
fast-dev-cli = "^0.15.1"
bandit = "^1.8.3"

[tool.poetry.group.ci.dependencies]
coveralls = {git = "https://github.com/waketzheng/coveralls-python", rev = "4.1.1"}

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # https://docs.astral.sh/ruff/rules/#pyupgrade-up
]

[tool.bandit]
exclude_dirs = ["tests", "fastapi_cdn_host/cli.py", "scripts", "examples", ".venv"]

[build-system]
requires = ["poetry-plugin-version"]
build-backend = "poetry_plugin_version.api"
